defmodule Doggo.Repo.Migrations.CreateShelterDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scheduled_shifts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :date, :date, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id, :uuid, null: false
    end

    create table(:recurring_shifts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :day_of_week, :bigint, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :start_date, :date
      add :end_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id, :uuid, null: false
    end

    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:scheduled_shifts) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "scheduled_shifts_location_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:scheduled_shifts, [:location_id])

    create unique_index(:scheduled_shifts, [:location_id, :date, :start_time, :end_time, :name],
             name: "scheduled_shifts_unique_scheduled_shift_time_index"
           )

    alter table(:recurring_shifts) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "recurring_shifts_location_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:recurring_shifts, [:location_id])

    alter table(:locations) do
      add :name, :text, null: false
      add :address, :text
      add :city, :text
      add :region, :text
      add :postal_code, :text
      add :country, :text, null: false, default: "USA"
      add :timezone, :text, null: false, default: "America/New_York"
      add :archived, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:locations, [:archived])

    create table(:enclosures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :status, :text, null: false, default: "available"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "enclosures_location_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:enclosures, [:location_id, :status])

    create index(:enclosures, [:location_id])
  end

  def down do
    drop_if_exists index(:enclosures, [:location_id])

    drop constraint(:enclosures, "enclosures_location_id_fkey")

    drop_if_exists index(:enclosures, [:location_id, :status])

    drop table(:enclosures)

    drop_if_exists index(:locations, [:archived])

    alter table(:locations) do
      remove :updated_at
      remove :inserted_at
      remove :archived
      remove :timezone
      remove :country
      remove :postal_code
      remove :region
      remove :city
      remove :address
      remove :name
    end

    drop_if_exists index(:recurring_shifts, [:location_id])

    drop constraint(:recurring_shifts, "recurring_shifts_location_id_fkey")

    alter table(:recurring_shifts) do
      modify :location_id, :uuid
    end

    drop_if_exists unique_index(
                     :scheduled_shifts,
                     [:location_id, :date, :start_time, :end_time, :name],
                     name: "scheduled_shifts_unique_scheduled_shift_time_index"
                   )

    drop_if_exists index(:scheduled_shifts, [:location_id])

    drop constraint(:scheduled_shifts, "scheduled_shifts_location_id_fkey")

    alter table(:scheduled_shifts) do
      modify :location_id, :uuid
    end

    drop table(:locations)

    drop table(:recurring_shifts)

    drop table(:scheduled_shifts)
  end
end
